# Generated by Django 5.0 on 2024-01-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0002_auto_20240106_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(unique=True, upload_to='media/'),
        ),
    ]
