# Generated by Django 5.0 on 2024-01-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0005_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
