# Generated by Django 5.0 on 2024-01-06 17:42

import django.core.validators
import imagekit.models.fields
import videoupload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0006_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default=videoupload.models.default_thumbnail, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(unique=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
