# Generated by Django 5.0 on 2024-01-06 21:33

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0008_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to='thumbnails/'),
        ),
    ]
