# Generated by Django 5.0 on 2024-01-06 21:35

import imagekit.models.fields
import videoupload.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0009_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default=videoupload.models.default_thumbnail, upload_to='media/thumbnails/'),
        ),
    ]
