# Generated by Django 5.0 on 2024-04-21 14:53

import videoupload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0011_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, default=videoupload.models.default_thumbnail, upload_to='thumbnails/'),
        ),
    ]
