# Generated by Django 5.0 on 2024-04-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0012_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
    ]
